pyeapi/api/mlag.py
test/system/test_api_mlag.py
test/system/test_api_stp.py

- Fix #24
- Add testcases to set port-channel for peer-link
- Change stp test to not use et1-7, just et1-4

Fix peer-link parsing regex

---

pyeapi/api/users.py
test/system/test_api_users.py
test/unit/test_api_users.py

- Close #31 - Adding support for sshkeys
- Fix #32 - set_privilege tests
- Fix #33 - set_role test tests
Note that there were no system tests for set_role.  Also, the system tests for set_privilege weren't prefixed with test_ so they were never run.

Add sshkey support to users API

---

pyeapi/api/routemaps.py
test/fixtures/running_config.routemaps
test/system/test_api_routemaps.py
test/unit/test_api_routemaps.py

This PR add support for managing route-maps.  This API includes the ability to:
- create, delete, default route-maps
- manage set statements
- manage match statements
- manage continue statement
Note that a routemap resource is uniquely identified by the combination of its name, action, and sequence number.

Add Routemap support

---

pyeapi/client.py

- Fix #35
- Note - the result key was adding to the dict when strict equals True.
The response key will be removed in a later version. Please update
any scripts that are using response.

Update enable return dict

---

pyeapi/api/staticroute.py
test/fixtures/running_config.text
test/system/test_api_staticroute.py
test/unit/test_api_staticroute.py

Add staticroute library with system/unit tests

Staticroute

---

pyeapi/client.py

* The RBAC and RADIUS compatibility do not allow short notations of
command. Hence elongating to full command.

Making configure RADIUS compatible

---

test/unit/test_client.py

Allows unit tests to run with mock 1.3.0.  Verified to still work with 1.0.1.

compatibility fix for current mock versions

---

pyeapi/api/abstract.py
pyeapi/client.py
test/system/test_api_interfaces.py
test/system/test_client.py

234: Refactor interfaces system tests - reorder tests so grouping makes a little more sense, add default and negate tests for set_description
268: Allow a config string to be passed to abstract.get_block for searching. defaults to 'running_config' which compares to node's running-config

Fix for redmine issues 234 and 268

---

pyeapi/api/bgp.py
test/unit/test_api_bgp.py

Make sure empty string handling is correct.
Most methods utilize the command_builder method for creating the command string, which currently interprets the empty string as a negation command. In this case, empty strings do produce a valid command.
The bgp module methods add/remove_network do not use the command_builder method, but build the command internally. This was the only instance where validation of input was required.

Redmine issue 648

---

pyeapi/eapilib.py

Performance fixes:
a) Send data using function arg 'message_body' to endheaders() and remove subsequent send().
b) Force buffering in getresponse() for 2.7.

Issue #18 performance fixes

---

pyeapi/client.py

We usually generate full configurations with jinja2 templates and pass them directly to the pyeapi without further processing (we do it via napalm as we have an environment with multiple vendors). The problem comes when we try to execute what you seem to call 'multiline' commands. This PR addresses this problem so you can do something like this:
>>> import pyeapi
>>> connection = pyeapi.client.connect(
...     transport='https',
...     host='192.168.56.201',
...     username='vagrant',
...     password='vagrant',
...     port=443,
...     timeout=60
... )
>>> device = pyeapi.client.Node(connection)
>>> device.run_commands('show hostname')
[{u'hostname': u'localhost', u'fqdn': u'localhost'}]
>>> device.run_commands('show banner login')
[{u'loginBanner': u''}]
>>> my_commands = [
... …

Added support for multiline commands without having to pass them as a dictionary

---

pyeapi/api/mlag.py
test/system/test_api_mlag.py
test/unit/test_api_mlag.py

fixes #91
Addresses arista-eosplus/ansible-eos#90
Release Note:
Include handling any character in domain-id string, including dot, hyphen, and space

Handle dot and hyphen in mlag domain-id string

---

pyeapi/client.py
pyeapi/eapilib.py
pyeapi/utils.py
test/unit/test_utils.py

fixes #93 
Release Notes:
Use logging instead of syslog for better cross-platform compatibility

Replace syslog calls with logging library

---

MANIFEST.in
pyeapi/api/ospf.py
test/fixtures/running_config.ospf
test/unit/test_api_ospf.py

Added OSPF to pyeapi.  Created unit tests and all tests ran without error.  Please feel free to critique and change if needed.
Thanks
Brian Goldberg

Added ospf scripts

---

test/unit/test_api_vlans.py

A random string (like '214') can be a valid VLAN. Fix the test case such that the not-so-random string can never be a VLAN.

Fix test case when random is a valid VLAN

---

pyeapi/api/interfaces.py
test/fixtures/running_config.vxlan
test/fixtures/vxlan.json
test/system/test_api_interfaces.py
test/system/test_client.py
test/unit/test_api_interfaces.py

fixes #105 
This is a bit of a strange corner case where when testing the ```vxlan mutlicast-group decap``` you can only run the system test on a Trident based system as this is the only system that supports this command.  However the default configuration in ```show run all int vxlan <x>``` has ```no vxlan multicast-group decap``` for all platforms and vEOS.  So I commented out the system test until we can have a mechanism to determine what platform we are running tests against.
Systest results:
$ make systest
Cleaning up distutils stuff
rm -rf build
rm -rf dist
rm -rf MANIFEST
rm -rf *.egg-info
Cleaning up byte compiled python stuff
find . -type f -regex ".*\.py[co]$" -delete
Cleaning up doc builds
rm -rf docs/_build
rm -rf docs/api_modules
rm -rf docs/client_modules
coverage run -m …

Update vxlan api

---

pyeapi/api/interfaces.py
pyeapi/client.py
test/lib/testlib.py
test/system/test_api_interfaces.py
test/system/test_api_ipinterfaces.py
test/system/test_api_routemaps.py
test/system/test_api_staticroute.py
test/system/test_api_stp.py
test/system/test_api_switchports.py
test/system/test_api_users.py
test/system/test_api_varp.py
test/unit/test_api_interfaces.py
test/unit/test_api_ipinterfaces.py
test/unit/test_api_ospf.py
test/unit/test_api_routemaps.py
test/unit/test_api_switchports.py
test/unit/test_api_system.py
test/unit/test_api_varp.py
test/unit/test_api_vlans.py
test/unit/test_client.py

This should help to configure LACP fallback in EOS https://eos.arista.com/configuring-port-channel-lacp-fallback-on-arista-switches/

expose portchannel attributes :lacp fallback, lacp fallback timeout

---

pyeapi/eapilib.py
test/system/test_client.py
test/unit/test_eapilib.py

Support autoComplete parameter when using execute from a connection.

Add support for autoComplete parameter. Issue 119

---

test/unit/test_api_ipinterfaces.py

A random string (like '214') can be a valid MTU. Fix the test case such
that the not-so-random string can never be a MTU.

Fix test case when random string is a valid MTU

---

pyeapi/eapilib.py

It breaks socket connections in napalm that use `pyeapi.client.connect` which can't specify the `path`
Fixes #141 and reverts #130

revert to pre-#130 static URI

---

pyeapi/api/bgp.py

Noticed a typo in bgp.py that could break `next-hop-self `.

Fixing typo in bgp.py

---

docs/configfile.rst
docs/quickstart.rst
pyeapi/client.py
pyeapi/eapilib.py
test/unit/test_client.py

Can provide cert_file, key_file and ca_file to connect method or via eapi.conf file.
Fixes #156

Add ability to use CA certs with EAPI connections

---

pyeapi/client.py

When we run commands below via eAPI, we'll see an error saying "Address 172.16.0.1 is already assigned to interface Ethernet6" at L7, and L1-L6 are committed.
However, sometimes I'd like to do this as an atomic operation, where abort everything when something goes wrong.
This PR will support that behavior with introducing `Node#configure_session()`.
```
1: interface Ethernet6
2:    no switchport
3:    ip address 172.16.0.1/30
4: !
5: interface Ethernet7
6:    no switchport
7:    ip address 172.16.0.1/30  ! Invalid
```
```json
{
"jsonrpc": "2.0",
"method": "runCmds",
"params": {
"format": "json",
"timestamps": false,
"autoComplete": false,
"expandAliases": false,
"cmds": [
"configure",
"interface Ethernet6",
"   no switchport",
"   ip address 172.16.0.1/30",
"interface Ethernet7",
"   no …
```

Support "configure session"

---

pyeapi/api/interfaces.py

Seems to be a long-standing couple of typos here (this feature will probably not have worked as a result)

Correct typo "mutlicast"

---

pyeapi/utils.py

Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
Solving #195

Inorrect import from 'collections' will stop working in Python 3.9

---

.travis.yml

I am part of IBM team and working on port power on cpu arch to this package as CI.
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,We typically build applications for customers and ISVs, and while we don't use this package directly, 
we do count on all of the packages in debian/ubuntu to build other packages. So we more likely have this as a second or third level dependency and couldn't tell you explicitly which features we use or our usage model,For more info tag @gerrith3.

Adding Power support(ppc64le)with continuous integration/testing to the  project for architecture independent

---

pyeapi/api/abstract.py

fixed issue #198, where the request was to let exception rise (`ConnectionError`) on connection failures (e.g. wrong credentials, wrong transport, etc).

fixed issue #198

---

pyeapi/api/vlans.py

if vlans in config are grouped, e.g.:
```
vlan 509-510,512
...
```
`getall()` should be able to match such case as well

#197 - updated vlans.getall() to handle vlan groupings

---

pyeapi/api/vlans.py
test/fixtures/running_config.text
test/unit/test_api_vlans.py

1. updated vlans.get() to return range/list of vlan ids (instead of input regex), e.g.:
```
vlans = connect.api('vlans')
vlans.get('200-.*')
{'vlan_id': '200-202,204', 'name': 'grouping', 'state': 'active', 'trunk_groups': []}
```
\- `vlan_id` now is resolved to the vlan line in config (`200-202,204`), rather than user's `200-.*`
2. updated relevant unit test

updated vlans.get() to return range/list of vlan ids

---

pyeapi/api/abstract.py

fixed annoying import warning when running systest:
```
test_add_entry (test_api_acl.TestApiExtendedAcls) ... /Users/dlyssenko/Work/My Work/> 2. ship EOS with pyeAPI module (bug457347)/pyeapi/pyeapi/api/abstract.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Callable, Mapping
```

fixed import warning in abstract module

---

docs/configfile.rst

Reverts arista-eosplus/pyeapi#205
reverting it, as the changes first must be made in the _develop_ branch (as it appears, *readthedocs* is sourced from the _develop_ branch too)

Revert "Master"

---

test/system/test_client.py

The deprecated aliases have been removed in python/cpython#28268 . Use `assertRegex` in Python 3 when present and fallback to the Python 2 alias.

Refactor deprecated unittest aliases for Python 3.11 compatibility.

---

pyeapi/api/switchports.py
test/fixtures/running_config.text
test/unit/test_api_switchports.py

This change fixes #215
Signed-off-by: DavidVentura <davidventura27@gmail.com>

Ignore subinterfaces on switchports.getall()

---

pyeapi/client.py

put a note in description of `client.connect()` method that scripts working fine in 3.9 and prior version will have a forward compatibility issue with python 3.10 (and above) when relying on `https` transport  - refer to the issue #222 for the details.

updated client description to reflect issue #222

---

test/unit/test_utils.py

in **python 3.10** `make unittest` is failing because `test/unit/test_utils.py` wasn't converted from using `collections.Iterable` into `collections.abc.Iterable`
\- Fixing that.

fixing collection.Iterables in test_utils.py for py3.10

---

pyeapi/api/users.py
test/unit/test_api_users.py

Modern versions of EOS allow one to specify a password that cannot be used to login which is useful for exclusive ssh-key auth:
```
vEOS(config)#username testuser secret ?
*       Specify a password that cannot be used to login
0       Specify an UNENCRYPTED password will follow
5       Specify an ENCRYPTED MD5 password will follow
LINE    The UNENCRYPTED (cleartext) password
sha512  Specifies an ENCRYPTED SHA512 password will follow
```
Currently pyeapi has no support for this. This change implements support for a `nologin` encryption type to support setting this feature via the api.

Add support for passwords that cannot be used to login

---

Makefile
pyeapi/eapilib.py

When user enables debugs and configures dut to use enable password, the user password is showing up in clear text in the debugs when any commands gets executed. This commit masks the user input.

removed password from showing in debugs

---

pyeapi/client.py
test/unit/test_client.py

Currently, the Node(conn).running_config always includes config defaults, this is not always wanted.
For example if you want to compare the running_config to the startup_config, it is easier to not have defaults included in the running_config.
With this option you can do something like this;
```
In [3]: conn = client.connect(**params)
In [4]: node = client.Node(conn, config_defaults=False)
In [5]: node.running_config.splitlines()[3:] == node.startup_config.splitlines()[4:]
Out[5]: True
```

Add option to not include defaults with node.running_config

---

pyeapi/client.py
test/unit/test_api_vrfs.py

Hi
The current parsing that splits the configuration from the device into sections is very slow. Running on a `DCS-7308-F` (with ~200 interfaces) this takes around **90 seconds**.
There are 2 reasons for that:
1- calling `getall()` on `api('switchports')` and `api('interfaces')` calls this twice
2- the regex approach is fairly slow, as it parses the whole config _for each interface_ (exacerbated by the first issue).
With this patch, the config is parsed once into sections. Looking at a flamegraph, it can still be improved however the impact on surrounding code would be a lot larger and the benefits are not that big (passing compiled objects or not compiling exact key matches like `interface Ethernet1`)
With this change applied, the parsing execution goes down to **2 seconds**.
The total …

Address performance issues on section splitting

---

.github/workflows/ci.yml
pyeapi/client.py

after PR #220 the `section()` call is able to mach on sections only and not on the sub-sections (sections does not have leading spaces, while sub-sections do).
This PR enhances the `section()` call so that it's possible to match on the sub-sections too. Here's an example. Consider the following config snippet:
```
logging event link-status global
!
mcs client
shutdown
!
cvx secondary default
shutdown
no server host
no source-interface
heartbeat-interval 20
heartbeat-timeout 60
no ssl profile
vrf default
!
```
the new behavior will be like this:
```
>>> c.section( 'event link-status' )
'logging event link-status global\n'
>>> 
>>> c.section( 'mcs client' )
'mcs client\n   shutdown\n   !\n   cvx secondary default\n      shutdown\n      no server host\n      no source-interface\n …
```

enhanced `section` to match subsections and removed py2.7 from CI

---

pyeapi/client.py
pyeapi/eapilib.py

Create a Session API mixin for Http and Https connection methods that
uses the /login endpoint to store a Cookie for all future connections.
This is useful when using centralized AAA to reduce the load of repeated
command calls.
Note that the cookie does have a lifetime, and that the connection will
stop working once the cookie lifetime expires, unless the authentication
method is manually called again

Support session-based authorization

---

pyeapi/api/abstract.py
pyeapi/client.py
pyeapi/utils.py

There are 2 possible approaches:
1. rely on the EOS version check (`self.version_number`) and then handle it respectingly
2. provide a programmatic interface to handle CLI variants why try-and-fail approach, where newer CLI is tried first and on the failed syntax a legacy (older) cli is tried
each approach has pros and cons: 
- for the 1st one, it's could be difficult to provide exact version matching for special and custom EOS versions.
- for the 2nd, the cli fetching turnaround (when running a newer pyeapi on an older EOS) would be longer, due to handling a failing (newer) variant of CLI  
This enhancement takes 2nd approach as the tradeoff for it is deemed reasonable and the handling approach would be more universal and code-wise cleaner.

provisioning for CLI variants to handle deprecated cli trasnitions

---

Makefile
pyeapi/api/ipinterfaces.py
pyeapi/client.py
pyeapi/eapilib.py
pyeapi/utils.py
test/fixtures/running_config.text
test/unit/test_api_ipinterfaces.py

implemented requests #161, added the respective unittest.

fix issue #161 - add parsing of secondary ip from interfaces

---

pyeapi/eapilib.py

Internal exceptions (error code 1001) currently do not have the actual error message included within `CommandError`, which hinders debugging.
Before
```
pyeapi.eapilib.CommandError: Error [1001]: CLI command 10 of 11 '   no shutdown' failed: internal error
```
After
```
pyeapi.eapilib.CommandError: Error [1001]: CLI command 10 of 11 '   no shutdown' failed: internal error [[Errno 13] Permission denied: '/usr/local/bin/foo']
```

Include error message in CommandError for internal exceptions

---

pyeapi/api/bgp.py

This will not only match AS number (i.e 65001) but also AS number in asdot notation (ie. 65001.10).

fix issue #255 (_parse_bgp_as regex to match as and asdot)

---

docs/Makefile
docs/conf.py
docs/generate_modules.py
pyeapi/api/ipinterfaces.py
pyeapi/api/ospf.py
pyeapi/utils.py

fixed some doc build issues and errors
provided docstring decorator:
- Docstrings cannot be interpolated. However, it's better to refer in the docstrings to defined constants by names rather than by values, so this decorator provides that functionality - it interpolates enumerated symbols. That way the docstrings in the source will refer to the constants by names, while upon building it will resolve and interpolate the values.

fixing doc build issues, errors, and providing docstring decorator

---

docs/requirements.rst
pyeapi/client.py
pyeapi/eapilib.py
pyeapi/utils.py
setup.py

Removed a reference to support for python2 and < python3.7

Removed reference to python2

---

.github/workflows/ci.yml
docs/release-notes-1.0.0.rst
test/lib/testlib.py
test/system/test_client.py
test/unit/test_client.py
test/unit/test_eapilib.py
test/unit/test_utils.py

fixed mock import and removed obsolete sys.version check

preparing for uplifting pyeapi in EOS

---

test/system/test_api_interfaces.py

When testing against a pool of real duts, some duts (supporting only up to 8 min-links) fail the test, hence adopting the change.

some physical duts supports only up to 8 min-link values

---

pyeapi/eapilib.py

Add an option to specify the API version as EOS doesn't return all VRFs for the command "show ip route vrf all summary" in version 1 of the API.
See Arista case 501384.
Example
`connection.execute('show ip route vrf all summary',apiVersion='latest')`

add apiVersion parameter

---

test/unit/test_client.py

`imp` is slated to be removed in Python 3.12.

Migrate to importlib

---

test/lib/systestlib.py

1. Dut's API gets list of all interfaces in `/pyeapi/api/interfaces.py` - it read those from `show run all`.
2. However, some interfaces present in the 'config all' might not be present on the actual dut.
3. This might create an issue during sytem test if `random_interface ()` picks an interface which is not currently present on the dut.
this PR should fix the issue

fixing system test issue where non-existent interface could be selected

---

test/system/test_api_interfaces.py

1. `test_api_mlag` runs after `test_api_interfaces`.  The latter selects a guinea-pig interface via `random_interface()` call
2. `test_api_mlag` always selects interface `Ethernet1` for its test. 
3. Thus, if `test_api_interfaces` picks `Ethernet1` by chance, it leaves it with flow-control configured, which breaks then mlag test
This trivial fix excludes  `Ethernet1` from being selected in `test_api_interfaces`

fixing system test issue where mlag test fails on Ethernet1

---

test/system/test_api_interfaces.py

Number of supported link in port-channels, keep growing. Hope newly defined invalid number will hold for a while.

updated number for invalid link
