pyeapi/api/ipinterfaces.py
pyeapi/api/switchports.py
pyeapi/api/vlans.py
pyeapi/client.py
pyeapi/eapilib.py
test/fixtures/dut.conf
test/system/test_api_ipinterfaces.py
test/system/test_api_switchports.py
test/system/test_api_vlans.py
test/unit/test_api_vlans.py

This PR provides some minor bug fixes to the API modules for ipinterfaces and switchports.  It also addes str and repr methods to the Node and Connection objects.

minor bug fixes to api modules

---

Makefile
pyeapi/api/varp.py
test/fixtures/running_config.varp
test/fixtures/running_config.varp_null
test/system/test_api_varp.py
test/unit/test_api_varp.py

- Manage virtual-router mac address
- Manage virtual-router ip addresses in Vlan interfaces

Add support for Varp API

---

pyeapi/api/interfaces.py
pyeapi/api/routemaps.py
test/fixtures/running_config.routemaps
test/unit/test_api_routemaps.py

This modifies the get and getall logic to return more comprehensive objects.  To keep with the Entity and EntityCollection classes, this API now only requires a get(name).

Feature routemap update

---

pyeapi/api/bgp.py
test/unit/test_api_bgp.py

Update _parse_shutdown method

---

pyeapi/api/vrrp.py
test/unit/test_api_vrrp.py

add key error checking to set_tracks

---

pyeapi/client.py
pyeapi/eapilib.py
test/system/test_client.py
test/unit/test_client.py
test/unit/test_eapilib.py

fix #7: add command error message for error types 1000, 1002, 1004
fix #37: update connect() to return a node object if requested

fix #7 and fix #37

---

pyeapi/api/acl.py
test/unit/test_api_acl.py

gave a shot to implementing issue #66

implement add ACE with seq nos

---

pyeapi/api/users.py
test/unit/test_api_users.py

- Close #19
- Add unittest to catch TypeError

Prevent API from trying to delete admin user

---

docs/install.rst

Add dev-requirements to install doc

---

pyeapi/client.py
pyeapi/utils.py
test/fixtures/eapi.conf.yaml
test/fixtures/env_path.conf
test/unit/test_client.py

Syslog a message on improperly formatted .conf file

---

pyeapi/api/staticroute.py
pyeapi/client.py
test/system/test_client.py
test/unit/test_client.py

Add some test cases and syntax cleanup for PR #78

Multiline cleanup

---

pyeapi/client.py
test/fixtures/eapi.conf
test/system/test_client.py
test/unit/test_client.py

Pass all args from connect_to to connect, then to Node creation.

---

pyeapi/client.py
test/system/test_client.py
test/unit/test_client.py

Node enable enhance

---

pyeapi/client.py
pyeapi/eapilib.py
test/system/test_client.py
test/unit/test_eapilib.py

and allow Node methods to send extra eAPI parameters. Fixes #126

Add support for eAPI expandAliases parameter

---

pyeapi/client.py
test/system/test_client.py
test/unit/test_client.py

Add node attributes from show version command

---

docs/examples.rst
docs/index.rst
docs/subinterfaces.rst
pyeapi/api/interfaces.py
test/system/test_api_interfaces.py
test/unit/test_api_interfaces.py

Add support for creating and deleting ethernet subinterfaces

---

pyeapi/api/acl.py
test/fixtures/running_config.text
test/system/test_api_acl.py
test/unit/test_api_acl.py

Add base extended ACL support.

---

pyeapi/utils.py
test/system/test_client.py
test/unit/test_client.py
test/unit/test_utils.py

Now sends full command.
Fixes #137

Fix bug where single unicode commands were sent one character at a time.

---

pyeapi/client.py
pyeapi/eapilib.py
test/system/test_client.py
test/unit/test_eapilib.py

Add more descriptive error message for eAPI socket errors.

---

pyeapi/eapilib.py
test/system/test_client.py
test/unit/test_eapilib.py

Add clearer error message for bad user credentials.

---

docs/quickstart.rst
pyeapi/utils.py
test/system/test_client.py
test/unit/test_client.py

Support eapi command revision syntax

---

pyeapi/eapilib.py

Remove leaked base64 authentication string in debug logs

---

pyeapi/eapilib.py

adding streaming option for commands

---

docs/configfile.rst

updated documentation to avoid using localhost for off-box connections

---

pyeapi/api/switchports.py

this is a trivial fix for the issue #213

fix for the issue #213

---

test/fixtures/running_config.text

extended config fixture to cover issue #213 in UT

extended config for unit testing issue #213

---

test/unit/test_api_switchports.py

My test (#216) on did not take into account a parallel branch (#217) - this PR addresses that oversight

Add new value from #213

---

pyeapi/eapilib.py

ujson and rapidjson are libraries that are
faster to encode and decode JSON objects

Try importing ujson and rapidjson before json

---

pyeapi/eapilib.py

This PR is fixing the issue where a user password is getting exposed in clear text in a traceback shall one occur due to incorrect credentials

fix passwd exposure in traceback issue

---

Makefile
dev-requirements.txt
pyeapi/api/abstract.py
pyeapi/api/interfaces.py
pyeapi/api/vlans.py
pyeapi/client.py
pyeapi/eapilib.py

readying pyeapi for switchover to GitHub actions, plus some minor style fixes to keep flake8 happy.

readying pyeapi for github actions + minor style fixes

---

.github/workflows/ci.yml

extended python-version list for CI with 2.7 and 3.10

---

pyeapi/api/ipinterfaces.py

a simple fix for the issue #210

fix for issue #210 - getall() fails in ipinterfaces module

---

pyeapi/api/interfaces.py

- flood list for vxlan in interfaces module returns wrong data

fix for issue #193

---

pyeapi/api/interfaces.py
pyeapi/client.py
pyeapi/eapilib.py
pyeapi/utils.py
test/fixtures/dut.conf
test/lib/testlib.py
test/system/test_api_interfaces.py
test/system/test_api_staticroute.py
test/system/test_api_vrfs.py
test/system/test_api_vrrp.py
test/system/test_client.py

there were a bunch of unit and system test failed (about 23 in total). This PR fixes all of them

fixed all failing unit-test and system tests

---

.readthedocs.yaml
MANIFEST.in
pyeapi/utils.py

This file is a new requirement for the `readthedocs.org` site.

Added required yaml documentation

---

docs/Makefile

this is an attempt to fix a missing modules section in readthedocs

forced modules generation for html format

---

dev-requirements.txt
setup.py

this project has swtiched to newer `unittest.mock`

cleanup old "mock" leftovers
